### ISSUE TITLE
script

### ISSUE THREAD

**Issue by Ghasedaak** [Azumi67/PortforwardSec#3]
سلام عزیز خسته نباشی میتونی این رو به شکل اسکریپت درش بیاری خیلی کمک میکنه برای فهمش
چون منم گیم بازی میکنم و برای استفاده شخصی میخوام الان اصلا نمیدونم کدوم سرویس شما رو باید استفاده کنم
اگر  پورت فروادر بهتری برای این کار هست یا تانلی هست که همه اینا رو با  هم انجام بده برای گیم به من معرفی کنید ممنون

**Comment by Azumi67** [comment]
سلام. من برای مدت زیادی از این پورت فوروارد استفاده کردم و مشکلی نداشتم. دارم بر روی پورت فوروارد دیگری کار میکنم و به زودی داخل گیم هم تستش میکنم 
در مورد اسکریپت هم که برای این پورت فوروارد آماده کردم ولی یادم رفته قرار بدم چون مشکلات تحصیلی دارم .

**Comment by Ghasedaak** [comment]
خب من چطور میتونم اسکریپت رو از شما بگیرم؟ چون  از این طریقی که توضیح دادید من خیلی گیج شدم ان شا الله مشکلات تحصیلیتون حل بشه 
ما شا الله تو این موارد بسیار کار بلد هستید خدا قوت
من ایدی تلگرام هم میذارم اگر بشه یه جوری با هم ارتباط بگیریم به من کمک کنید خیلی ممنون میشم
چون تو یوتیوب اصلا  آموزa های درستی نیست و همه کپی میکنن از همدیگه و اونایی هم که کار بلد هستن  چیزی ارائه نمیدن یا اگرم میدن ما نمیدونیم کجاست و برای همین اینجوری دستمون تو پوست گردو میممونه برای یه پورت فروارد گیمینگ

My Telegram Id : @Yaadeegarri
